curriculum_design_task:
  description: >
    Analyze the topic "{topic}" and the user's desired complexity level: {complexity_level}.
    Create a detailed course outline with logical module and section breakdowns. 
    Make sure to cover core concepts and progression appropriate for the selected level of depth.
  expected_output: >
    A course outline consisting of:
    - 4 to 8 sections (modules)
    - Each section with a short title and 1-2 sentence description
    Format the output as a bullet list using markdown.
  agent: curriculum_designer

content_creation_task:
  description: >
    Based on the generated course outline for the topic "{topic}", write in-depth course content for each section.
    Include explanations, examples, and real-world context where applicable. Use educational tone suitable for {complexity_level} learners.
  expected_output: >
    A full course content draft where each section from the outline has:
    - A title
    - 4 to 6 well-structured paragraphs explaining the topic
    - Markdown format with headings, subheadings, and bullet points if necessary
  agent: content_creator

quiz_generation_task:
  description: >
    For each section in the {topic} course, create 2 to 4 quiz questions that test the learner’s understanding.
    Vary question types (MCQs, true/false, short answer) and provide clear answers and explanations.
  expected_output: >
    A list of quizzes grouped by section.
    Each quiz item should include:
    - Question
    - 2–4 answer choices (if applicable)
    - Correct answer
    - Short explanation
    Use markdown formatting.
  agent: quiz_master

content_editing_task:
  description: >
    Review and refine the drafted {topic} course content.
    Improve flow, grammar, tone, and clarity while preserving the meaning.
    Ensure consistent formatting, terminology, and readability appropriate for {complexity_level}.
  expected_output: >
    A polished version of the full course content in markdown format, cleaned for clarity and readability.
  agent: content_editor

formatting_task:
  description: >
    Convert the finalized course content on "{topic}" into the desired format: {format}.
    Ensure clean formatting, readable structure, and compatibility with common e-readers or document tools.
  expected_output: >
    A single output file (or string if rendering inline) representing the course in {format} format.
    It should be clean, organized, and downloadable.
  agent: format_agent

feedback_loop_task:
  description: >
    Gather feedback from the user regarding the {topic} course outline and content.
    Identify which parts need changes or improvement and coordinate with the appropriate agents to update the material.
  expected_output: >
    A list of user-requested changes and a plan for revising the course content accordingly.
    Optionally, regenerate relevant sections or quizzes based on feedback.
  agent: feedback_agent


# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
